#!/bin/sh

MULTIARCHLIBDIR=/usr/lib/`gcc -dumpmachine`

if [ -e ${MULTIARCHLIBDIR}/libhidapi-hidraw.a ]; then
  ln -s -f ${MULTIARCHLIBDIR}/libhidapi-hidraw.a  /usr/local/lib/libhidapi.a
fi

if [ -e ${MULTIARCHLIBDIR}/libhidapi-hidraw.so ]; then
  ln -s -f ${MULTIARCHLIBDIR}/libhidapi-hidraw.so  /usr/local/lib/libhidapi.so
fi

ldconfig
