name = "libsimpleio_static_examples"
description = "Example programs using the libsimpleio_static library crate"
version = "@@VERSION@@"
licenses = "BSD-1-Clause"
website = "https://github.com/pmunts/libsimpleio"

authors = ["Philip Munts"]
maintainers = ["Philip Munts <phil@munts.net>"]
maintainers-logins = ["pmunts"]

project-files = ["test_hello.gpr"]

executables = ["test_hello"]

tags = ["embedded", "linux", "libsimpleio", "beaglebone", "pocketbeagle", "raspberrypi"]
