#!/bin/sh

# Create an Ada program project using the Linux Simple I/O Library

# Copyright (C)2021-2023, Philip Munts dba Munts Technologies.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

# Validate parameters

if [ "${1}" = "--allcaps" ]; then
  # Render Ada keywords in all capital letters.  Most people won"t want
  # this, but I prefer it.
  ALLCAPS=yes
  shift 1
fi

if [ "${1}" = "--nogit" ]; then
  # Do not create git repository
  NOGIT=yes
  shift 1
fi

if [ $# -lt 2 -o $# -gt 3 ]; then
  echo ""
  echo "Ada Program Project Creator"
  echo ""
  echo "Usage: <name> <kind> [<target>]"
  echo ""
  echo "<kind> may be any of: libsimpleio remoteio mcp2221 ftdi/mpsse"
  echo ""
  echo "<target> may be any of: BeagleBone PocketBeagle RaspberryPi1"
  echo "  RaspberryPi2 RaspberryPi3 RaspberryPi4"
  echo ""
  exit 1
fi

LIBSIMPLEIO=${LIBSIMPLEIO:-/usr/local/share/libsimpleio}
NAME=${1}
KIND=${2}
TARGET=${3:-NONE}
DSTDIR=./${NAME}

# Validate parameters

if [ -d ${DSTDIR} ]; then
  echo ""
  echo "ERROR: project directory already exists.";
  echo ""
  exit 1
fi

case ${KIND} in
  libsimpleio|remoteio|mcp2221|ftdi_mpsse)
  ;;

  *)
    echo ""
    echo "ERROR: Invalid project kind."
    echo ""
    exit 1
  ;;
esac

case ${TARGET} in
  BeagleBone|PocketBeagle|RaspberryPi1|RaspberryPi2|RaspberryPi3|RaspberryPi4|NONE)
  ;;

  *)
    echo ""
    echo "ERROR: Invalid target value."
    echo ""
    exit 1
  ;;
esac

# Populate the project skeleton

mkdir -p					${DSTDIR}/.vscode
cp ${LIBSIMPLEIO}/ada/projects/Makefile		${DSTDIR}
cp ${LIBSIMPLEIO}/ada/code/tasks.json		${DSTDIR}/.vscode

# Copy applicable default.gpr

case ${KIND} in
  libsimpleio)
    sed "1,23d" < ${LIBSIMPLEIO}/ada/programs/default.gpr > ${DSTDIR}/default.gpr
  ;;

  remoteio|mcp2221)
    sed "1,23d" < ${LIBSIMPLEIO}/ada/programs/${KIND}/default.gpr > ${DSTDIR}/default.gpr
  ;;

  ftdi_mpsse)
    sed "1,23d" < ${LIBSIMPLEIO}/ada/programs/ftdi/mpsse/default.gpr > ${DSTDIR}/default.gpr
  ;;
esac

# Copy applicable default.cgpr

case ${TARGET} in
  BeagleBone)
    cp /usr/local/gcc-arm-linux-gnueabihf-muntsos-beaglebone/share/gpr/BeagleBone.cgpr ${DSTDIR}/default.cgpr
  ;;

  PocketBeagle)
    cp /usr/local/gcc-arm-linux-gnueabihf-muntsos-beaglebone/share/gpr/BeagleBone.cgpr ${DSTDIR}/default.cgpr
  ;;

  RaspberryPi1)
    cp /usr/local/gcc-arm-linux-gnueabihf-muntsos-raspberrypi1/share/gpr/${TARGET}.cgpr ${DSTDIR}/default.cgpr
  ;;

  RaspberryPi2)
    cp /usr/local/gcc-arm-linux-gnueabihf-muntsos-raspberrypi2/share/gpr/${TARGET}.cgpr ${DSTDIR}/default.cgpr
  ;;

  RaspberryPi3)
    cp /usr/local/gcc-aarch64-linux-gnu-muntsos/share/gpr/${TARGET}.cgpr ${DSTDIR}/default.cgpr
  ;;

  RaspberryPi4)
    cp /usr/local/gcc-aarch64-linux-gnu-muntsos/share/gpr/${TARGET}.cgpr ${DSTDIR}/default.cgpr
  ;;
esac

# Copy stub main program file

if [ "$ALLCAPS" = "yes" ]; then
  # Phil"s preference: Keywords are all caps and indentation is 2 spaces
  cat <<EOD > ${DSTDIR}/${NAME}.adb
PROCEDURE @@NAME@@ IS

BEGIN
  NULL;
END @@NAME@@;
EOD
else
  # AdaCore"s preference: Keywords are lower case and indentation is 3 spaces
  cat <<EOD > ${DSTDIR}/${NAME}.adb
procedure @@NAME@@ is

begin
   null;
end @@NAME@@;
EOD
fi

# Expand @@NAME@@ and @@KIND@@ in the project files

sed -i "s/@@NAME@@/${NAME}/g" ${DSTDIR}/*
sed -i "s/@@KIND@@/${KIND}/g" ${DSTDIR}/*

# Fixup permissions

find ${NAME} -type d -exec chmod 755 {} ";"
find ${NAME} -type f -exec chmod 644 {} ";"

# Create git repository, if desired

hash git >/dev/null 2>&1

if [ $? -eq 0 -a "$NOGIT" != "yes" ]; then
  cd ${NAME}
  git init -q
  git add .
  git commit -q -m "Initial project skeleton."
fi
