.\" man page for Munts Technologies Linux Simple I/O Library
.\" libevent event notification module
.\"
.\" $Id$
.\"
.\" Copyright (C)2016, Philip Munts, President, Munts AM Corp.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\" * Redistributions of source code must retain the above copyright notice,
.\"   this list of conditions and the following disclaimer.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
.\" LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.TH libevent 2 "2 March 2016" "version 1.0" "Linux Simple I/O Library"
.SH NAME
.B libevent
\-\- Linux Simple I/O Library: Event Notification Module
.SH SYNOPSIS
.nf
.B #include <libevent.h>
.sp
.BI "void EVENT_init(int *" error ");"
.BI "void EVENT_close(int *" error ");"
.BI "void EVENT_register_fd(int " fd ", int " events ", int *" error ");"
.BI "void EVENT_unregister_fd(int " fd ", int *" error ");"
.BI "void EVENT_wait(int *" fd ", int *" event ", int " timeoutms ", int *" error ");"
.fi
.sp
Link with
.B -lsimpleio
.SH DESCRIPTION
All functions return
.B 0
in
.I *error
upon success or an
.B errno
value in
.I *error
upon failure.
.PP
.B EVENT_init()
must be called before any of the other functions.
.PP
.B EVENT_close()
may be called to release any internal resources previously acquired by
.BR EVENT_init() .
.PP
.B EVENT_register_fd()
may be called to register
.B epoll(7)
event notifications for the given file descriptor
.IR fd .
Event codes such as
.B EPOLLIN
(input ready) are defined in the
.B /usr/include/sys/epoll.h
header file.
.PP
.B EVENT_unregister_fd()
may be called to unregister event notifications for the given file descriptor
.IR fd .
.PP
.B EVENT_wait()
may be called to wait until an event notification occurs.  The
.I timeoutms
parameter indicates the time in milliseconds to wait for a notfication.  If
a notification occurs before the timeout expires,
.I *error
is set to
.B 0
and
.I *fd
and
.I *event
are set to the next available file descriptor and event code.
If no notification occurs
before the timeout expires,
.I *error
is set to
.B EAGAIN
and
.I *fd
and
.I *event
are invalid.
.SH SEE ALSO
.BR libsimpleio "(2), " libgpio "(2), " libhidraw "(2), " libi2c "(2), " libserial "(2),"
.br
.BR libspi "(2)"
.SH AUTHOR
Philip Munts, President, Munts AM Corp dba Munts Technologies
