.\" man page for Munts Technologies Linux Simple I/O Library
.\" Linux syscall wrapper module
.\"
.\" Copyright (C)2016, Philip Munts, President, Munts AM Corp.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\" * Redistributions of source code must retain the above copyright notice,
.\"   this list of conditions and the following disclaimer.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
.\" LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.TH liblinux 2 "6 October 2016" "version 1.0" "Linux Simple I/O Library"
.SH NAME
.B liblinux
\-\- Linux Simple I/O Library: Linux System Call Wrapper Module
.SH SYNOPSIS
.nf
.B #include <liblinux.h>

.BI "void LINUX_detach(int32_t *" error ");"

.BI "void LINUX_drop_privileges(const char *" username ", int32_t *" error ");"

.BI "void LINUX_openlog(const char *" id ", int32_t " options ", int32_t " facility ", int32_t *" error ");"

.BI "void LINUX_syslog(int32_t " priority ", const char *" msg ", int32_t *" error ");"

.fi
Link with
.BR -lsimpleio .
.SH DESCRIPTION
.nh
These functions wrap certain useful Linux system calls for use by other
programming languages such as Ada, Pascal, and Java.  They are provided
for the convenience of devlopers using
.B libsimpleio
with those langauges.  For the C programming language, they offer no
particular benefit over the regular system call wrappers.
.PP
All functions return either
.B 0
(upon success) or an
.B errno
value (upon failure) in
.IR *error .
.PP
.B LINUX_detach()
detaches the calling process from its controlling terminal and continues
execution in the background.
.PP
.B LINUX_drop_privileges()
allows a process started by the superuser to drop its privileges to those
of the user specified by the
.I username
parameter.
.PP
.B LINUX_openlog()
opens a connection to the
.B syslog
message logger.  The
.IR options " and " facility
parameters accept the same values as the
.B openlog()
system library function.
.PP
.B LINUX_syslog()
transmits a text message supplied in the
.I msg
parameter to the
.B syslog
message logger. The
.I priority
parameter accepts the same values as the 
.B syslog()
system library function.
.SH SEE ALSO
.BR libsimpleio "(2), " libevent "(2), " libgpio "(2), " libhidraw "(2), " libi2c "(2), "
.br
.BR liblinx "(2), " libserial "(2), " libspi "(2), " libstream "(2), " libtcp4 "(2)"
.SH AUTHOR
Philip Munts, President, Munts AM Corp dba Munts Technologies
