.\" man page for Munts Technologies Linux Simple I/O Library
.\"
.\" Copyright (C)2016-2017, Philip Munts, President, Munts AM Corp.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are met:
.\"
.\" * Redistributions of source code must retain the above copyright notice,
.\"   this list of conditions and the following disclaimer.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
.\" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
.\" LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
.\" SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
.\" INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
.\" ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
.\" POSSIBILITY OF SUCH DAMAGE.
.\"
.TH libsimpleio 2 "3 August 2017" "version 1.1" "Linux Simple I/O Library"
.SH NAME
.BR libsimpleio
\-\- Linux Simple I/O Library
.SH DESCRIPTION
.nh
.BR libsimpleio
is an attempt to encapsulate (as much as possible) the ugliness of Linux I/O
device access. It provides services for reading and/or writing the following
types of devices:

* GPIO (General Purpose Input/Output) Pins
.br
* Raw HID (Human Interface Device) Devices
.br
* I\u\s-22\s+2\dC (Inter-Integrated Circuit) Bus Devices
.br
* LabView LINX Remote I/O Devices
.br
* PWM (Pulse Width Modulated) Output Devices
.br
* Serial Ports
.br
* SPI (Serial Peripheral Interface) Bus Devices
.br
* Stream Framing Protocol Devices
.br
* TCP and UDP over IPv4 Network Devices
.br
* Watchdog Timer Devices
.PP
Although
.BR libsimpleio
was originally intended for Linux microcomputers such as the Raspberry Pi,
it can also be useful on larger desktop Linux systems.
.SH SEE ALSO
.BR libevent "(2), " libgpio "(2), " libhidraw "(2), " libi2c "(2), " libipv4 "(2),"
.br
.BR liblinux "(2), " liblinx "(2), " libpwm "(2), " libserial "(2), " libspi "(2),"
.br
.BR libstream "(2), " libwatchdog "(2)"
.PP
.B http://git.munts.com/libsimpleio/doc/UserManual.pdf
.SH AUTHOR
Philip Munts, President, Munts AM Corp dba Munts Technologies
