#!/bin/sh

# udev helper script for creating and removing /dev/pwm-X:Y symlink

# Copyright (C)2018, Philip Munts, President, Munts AM Corp.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

SetPerms()
{
  chown root:plugdev $1
  chmod $2 $1
}

DEVNAME=`basename ${DEVPATH}`

# Handle PWM chip event

echo ${DEVNAME} | egrep 'pwmchip[0-9]+'
if [ $? -eq 0 ]; then
  if [ "${ACTION}" = "add" ]; then
    SetPerms /sys${DEVPATH}          0750
    SetPerms /sys${DEVPATH}/export   0220
    SetPerms /sys${DEVPATH}/npwm     0440
    SetPerms /sys${DEVPATH}/unexport 0220
    exit 0
  fi

  exit 0
fi

PARENTPATH=`dirname ${DEVPATH}`
PARENTNAME=`basename ${PARENTPATH}`

echo ${PARENTNAME}| egrep 'pwmchip[0-9]+'
if [ $? -eq 0 ]; then
  CHIP=`echo ${PARENTNAME} | cut -c 8-`
fi

echo ${DEVNAME} | egrep 'pwm[0-9]+'
if [ $? -eq 0 ]; then
  CHAN=`echo ${DEVNAME} | sed 's/pwm//g'`
fi

echo ${DEVNAME} | egrep 'pwm\-[0-9]+:[0-9]+'
if [ $? -eq 0 ]; then
  CHAN=`echo ${DEVNAME} | sed -r 's/pwm-[0-9]+://g'`
fi

# Handle PWM channel event

if [ -n "${CHIP}" -a "${CHAN}" ]; then
  if [ "${ACTION}" = "add" ]; then
    SetPerms /sys${DEVPATH}            0750
    SetPerms /sys${DEVPATH}/capture    0440
    SetPerms /sys${DEVPATH}/duty_cycle 0660
    SetPerms /sys${DEVPATH}/enable     0660
    SetPerms /sys${DEVPATH}/period     0660
    SetPerms /sys${DEVPATH}/polarity   0660

    ln -s /sys${DEVPATH} /dev/pwm-${CHIP}:${CHAN}
    exit 0
  fi

  if [ "${ACTION}" = "remove" ]; then
    rm /dev/pwm-${CHIP}:${CHAN}
    exit 0
  fi
fi
