#! /usr/bin/python3

# MUNTS-0018 Raspberry Pi Tutorial I/O Board Motor Test

# Copyright (C)2024, Philip Munts dba Munts Technologies.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

from time                         import sleep
from munts.libsimpleio.munts_0018 import MotorOutputFactory, J6PWM, J6DIR
from munts.common                 import irange

print("\nMUNTS-0018 Raspberry Pi Tutorial I/O Board Motor Test\n")

outp = MotorOutputFactory(J6PWM, J6DIR, 1000)

# Sweep velocity up and down

for V in irange(0, 100, 1):
  outp.velocity = float(V/100.0)
  sleep(0.05)

for V in irange(100, -100, -1):
  outp.velocity = float(V/100.0)
  sleep(0.05)

for V in irange(-100, 0, 1):
  outp.velocity = float(V/100.0)
  sleep(0.05)
