#! /usr/bin/python3

# MUNTS-0018 Raspberry Pi Tutorial I/O Board Button and LED Test

# Copyright (C)2024, Philip Munts dba Munts Technologies.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

from munts.interfaces.gpio        import Direction
from munts.libsimpleio.munts_0018 import GPIOPinFactory, BTN1, LED1
from time                         import sleep

print("\nMUNTS-0018 Raspberry Pi Tutorial I/O Board Button and LED Test\n")

# Create GPIO pin objects

LED    = GPIOPinFactory(LED1, Direction.Output)
Button = GPIOPinFactory(BTN1, Direction.Input)

# Force initial detection

oldstate = not Button.state

# Main event loop -- handle button presses

while True:
  newstate = Button.state

  # Handle change in button state

  if newstate != oldstate:
    if newstate:
      print("PRESSED")
      LED.state = True
    else:
      print("RELEASED")
      LED.state = False

  oldstate = newstate
