#! /usr/bin/python3

# Motor Driver Output Test using libsimpleio

# Copyright (C)2024, Philip Munts.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# * Redistributions of source code must retain the above copyright notice,
#   this list of conditions and the following disclaimer.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
# LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

import munts.motor1
import munts.libsimpleio.gpio
import munts.libsimpleio.pwm
import munts.libsimpleio.raspberrypi
import time

from munts.common import irange

print("\nMotor Driver Output Test using libsimpleio\n")

# Create PWM output object for speed control

speed     = munts.libsimpleio.pwm.Output(munts.libsimpleio.raspberrypi.PWM0, 1000)

# Create GPIO output pin object for direction control

direction = munts.libsimpleio.gpio.Pin(munts.libsimpleio.raspberrypi.GPIO13,
  munts.libsimpleio.gpio.Direction.Output)

# Create a motor driver output object

outp      = munts.motor1.Output(speed, direction)

# Sweep velocity up and down

for V in irange(0, 100, 1):
  outp.velocity = float(V/100.0)
  time.sleep(0.05)

for V in irange(100, -100, -1):
  outp.velocity = float(V)
  time.sleep(0.05)

for V in irange(-100, 0, 1):
  outp.velocity = float(V/100.0)
  time.sleep(0.05)
